version: "3"


services:


###############################################
# containers con1 to con7 serve as infrastructure to be ansible hosts
###############################################

  con1: 
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "9093:9092"
    privileged: true
    entrypoint: ["/usr/sbin/init"]
      
  con2:
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "9092:9092"
      - "8091:8090"
    privileged: true
    entrypoint: ["/usr/sbin/init"]

  con3:
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "8081:8081"
    privileged: true
    entrypoint: ["/usr/sbin/init"]

  con4:
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "8083:8083"
    privileged: true
    entrypoint: ["/usr/sbin/init"]

  con5:
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "9021:9021"
    privileged: true
    entrypoint: ["/usr/sbin/init"]
      
  con6:
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "8088:8088"
    privileged: true
    entrypoint: ["/usr/sbin/init"]

  con7:
    networks:
      - mima-net-rbac
    tty: true
    build: .
    expose:
      - "22"
    ports:
      - "9094:9092"
      - "8090:8090"
    privileged: true
    entrypoint: ["/usr/sbin/init"]
  
#########################################
# container with convenient kafka tools
#########################################
    
  tools:
    image: cnfldemos/tools:0.3
    hostname: tools
    container_name: tools
    entrypoint: /bin/bash
    tty: true
    networks:
      - mima-net-rbac
    
#########################################
# containers with openldap and corresponding UI
#########################################

  openldap:
    networks:
      - mima-net-rbac
    image: osixia/openldap:1.3.0
    hostname: openldap
    container_name: openldap
    environment:
        LDAP_ORGANISATION: "mimacomDemo"
        LDAP_DOMAIN: "mimacomdemo.com"
        LDAP_BASE_DN: "dc=mimacomdemo,dc=com"
#        LDAP_ADMIN_USERNAME: admin
#        LDAP_ADMIN_PASSWORD: admin
    volumes:
# containes predefined groups and users
        - ./scripts/security/ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service --loglevel debug"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "8010:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - mima-net-rbac
      
###############################################
# this is where ansible runs from
###############################################
  bastion:
    image: alpine/ansible
    entrypoint: /bin/bash
    networks:
      - mima-net-rbac
    tty: true
    volumes:
      - ./:/etc/data
    
networks:
  mima-net-rbac:
    driver: bridge