kafka_controller:
  hosts:
    con1:
  vars:
    kafka_controller_log_dir: "{{general_log_path}}"

schema_registry:
  hosts:
    con3:
  vars:
    schema_registry_log_dir: "{{general_log_path}}"

kafka_connect:
  hosts:
    con4:
  vars:
    kafka_connect_log_dir: "{{general_log_path}}"

control_center:
  hosts:
    con5:
  vars:
    control_center_log_dir: "{{general_log_path}}"
    control_center_default_internal_replication_factor: 1
    
ksql:
  hosts:
    con6:
  vars:
    ksql_log_dir: "{{general_log_path}}"
    confluent.support.metrics.enable: false

kafka_broker:
  hosts:
    con2:
    con7:
  vars:
    kafka_broker_log_dir: "{{general_log_path}}"
    kafka_broker_custom_listeners:
      service_listener:
        name: SERVICE
        port: 9093
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: plain

all:
  vars:
    general_log_path: "/var/log/kafka"
    validate_hosts: true
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: root123
    #    ansible_become: true

    super_user: User:ksqlDBUser

#    kafka_broker_configure_multiple_listeners: false
    ssl_enabled: false
    schema_registry_ssl_enabled: false
    sasl_protocol: plain
    
    rbac_enabled: true
    mds_retries: 5
    mds_super_user: mds
    mds_super_user_password: mds
  
    kafka_controller_health_checks_enabled: false
    kafka_broker_ldap_user: admin
    kafka_broker_ldap_password: admin
    kafka_controller_ldap_user: admin
    kafka_controller_ldap_password: admin
    schema_registry_ldap_user: schemaregistryUser
    schema_registry_ldap_password: schemaregistryUser
    kafka_connect_ldap_user: connectAdmin
    kafka_connect_ldap_password: connectAdmin
    ksql_ldap_user: ksqlDBAdmin
    ksql_ldap_password: ksqlDBAdmin
    # kafka_rest_ldap_user: rest_proxy
    # kafka_rest_ldap_password: password
    control_center_ldap_user: controlcenterAdmin
    control_center_ldap_password: controlcenterAdmin
    

    
    jmxexporter_enabled: true
    jolokia_enabled: true
   
    kafka_controller_custom_properties:
      log.dirs: /var/dataa
      
      
    kafka_controller_sasl_protocol: plain
    ksql_log_streaming_enabled: true
    kafka_broker_custom_properties:
      log.dirs: /var/dataa 
      listener.name.service.plain.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required;
      listener.name.service.plain.sasl.server.callback.handler.class: io.confluent.security.auth.provider.ldap.LdapAuthenticateCallbackHandler
          
      ldap.java.naming.factory.initial: com.sun.jndi.ldap.LdapCtxFactory
      ldap.com.sun.jndi.ldap.read.timeout: 3000
      ldap.java.naming.provider.url: ldap://openldap:389
      ldap.java.naming.security.principal: cn=admin,dc=mimacomdemo,dc=com
      ldap.java.naming.security.credentials: admin
      ldap.java.naming.security.authentication: simple
      ldap.user.search.base: ou=users,dc=mimacomdemo,dc=com
      ldap.group.search.base: ou=groups,dc=mimacomdemo,dc=com
      ldap.group.search.mode: GROUPS
      ldap.user.name.attribute: uid
      ldap.user.memberof.attribute.pattern: cn=(.*),ou=users,dc=mimacomdemo,dc=com
      ldap.group.name.attribute: cn
      ldap.group.member.attribute.pattern: memberUid
      ldap.user.object.class: inetOrgPerson